[package]
name = "serialmate"
version = "1.0.0"
description = "SerialMate - 串口调试助手"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "serialmate_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-serialplugin = "2.21.1"
tauri-plugin-tcp = "0.1.2"
tauri-plugin-udp = "0.1.1"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
local-ip-address = "0.6"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_LibraryLoader", "Win32_Devices_DeviceAndDriverInstallation", "Win32_Graphics_Gdi"] }

[patch.crates-io]
# 使用本地 vendored 版本，修复了 send 锁死问题和添加了 200ms 数据缓冲
tauri-plugin-tcp = { path = "vendor/tauri-plugin-tcp" }

